### ISSUE TITLE
No GUI on Ubuntu 14.04

### ISSUE THREAD

**Issue by cibersheep** [bluszcz/PureDataStepSequencer#1]
Nice sequencer.
I have an issue trying to open PDSS on Ubuntu 14.04, I open it in pure data and I get this mesage:
" gui
... couldn't create"

so I tried to open /patches/GUI.pd it does'n get buttons on the right (no play, reset, etc)... the rest is working though

**Comment by cibersheep** [comment]
OK. It's something very easy to fix: in Main.pd where GUI.pd is called, shuold be in capitals GUI (in linux capital letters are important)

**Comment by cibersheep** [comment]
Row.pd 59 0 7 0 (inlet->loadbang) connection failed
GUI.pd 157 0 126 0 (bng->loadbang) connection failed
warning: row04: multiply defined

**Comment by luci1mwm** [comment]
hi,
hope u are still living a good life in 2023. 2014 seems far now... MAybe u are still using PD nowadays ? if yes did you found an answer to the last tree problems u pointed? BYE;;) ... from the futur**-**><
